### ISSUE TITLE
NoSuchMethodError org.tartarus.snowball.ext.englishStemmer.eq_s

### ISSUE THREAD

**Issue by fgiasson** [weavejester/snowball-stemmer#2]
I am not sure why, but every time I try to step a word, I am getting this error:

```
NoSuchMethodError org.tartarus.snowball.ext.englishStemmer.eq_s(ILjava/lang/String;)Z  org.tartarus.snowball.ext.englishStemmer.r_prelude (englishStemmer.java:194)
```

But everything seems good from the Java files. I thought it may be the Clojar lib, but I recompiled locally using `lein install` and the same happen.

Any ideas?

**Comment by provtimofei** [comment]
I solved this problem by putting this package before the Lucene (actually first) in classpath.
